name: Richard Bishop
description: Sharing my experiences and thoughts about Ruby on Rails, Test-driven Development, Software Design and Developing with Agility
markdown: redcarpet
highlighter: pygments
url: http://rubiquity.com
