name: Richard Bishop
description: A programmer with interests in programming languages, concepts and tools that make my life better. Known to blabber on endlessly about concurrency and DevOps.
markdown: redcarpet
highlighter: pygments
url: http://rubiquity.com
timezone: UTC
