#! /bin/bash

apt-get -y install clang libpcre3-dev openssl-dev zlib1g-dev make jq

git clone --depth 1 --branch release-1.15.10 https://github.com/nginx/nginx /tmp/nginx

cd /tmp/nginx
./auto/configure --prefix=/var/nginx \
            --with-cc=/usr/bin/clang \
            --with-cpp=/usr/bin/clang \
            --with-threads \
            --with-file-aio \
            --with-http_ssl_module \
            --with-http_v2_module \
            --with-http_gzip_static_module \
            --with-pcre \
            --without-http_ssi_module \
            --without-http_userid_module \
            --without-http_access_module \
            --without-http_auth_basic_module \
            --without-http_mirror_module \
            --without-http_autoindex_module \
            --without-http_geo_module \
            --without-http_map_module \
            --without-http_split_clients_module \
            --without-http_referer_module \
            --without-http_fastcgi_module \
            --without-http_uwsgi_module \
            --without-http_scgi_module \
            --without-http_grpc_module \
            --without-http_memcached_module \
            --without-http_limit_conn_module \
            --without-http_limit_req_module \
            --without-http_empty_gif_module \
            --without-http_browser_module \
            --without-http_upstream_hash_module \
            --without-http_upstream_ip_hash_module \
            --without-http_upstream_least_conn_module \
            --without-http_upstream_keepalive_module \
            --without-http_upstream_zone_module

make
make install
